apiVersion: v1
kind: Namespace
metadata:
  name: serverless
  labels:
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/part-of: serverless-demo
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: serverless-demo
  namespace: serverless
spec:
  template:
    metadata:
      annotations:
        # Target 10 in-flight-requests per pod.
        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: dev.local/demo/k8s-serverless-demo:1.0-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              protocol: TCP